### ISSUE TITLE
Add precise accuracy handling to shooting range

### ISSUE THREAD

**Issue by jonpas** [Theseus-Aegis/Mods#215]
Per-part handling of percentage, head shot > leg shot... etc.

**Comment by SyMP2005** [comment]
To clarify, this is accuracy per target depending on where the shot lands.
The hit shot would be awarded a percentage/points depending on where the body part that is hit.

Accuracy zones from highest to lowest importance:
Head > Torso > Arms & Legs (No difference between those two, although you could say less points for legs)

Percentages for the above:
Head (100%) > Chest (75%) > Arms & Legs (35%)

This is just a thought of course, more thoughts are welcome!

**Comment by jonpas** [comment]
No use for it at the moment, and probably won't happen with current version of the Shooting Range component.
