### ISSUE TITLE
Check 40mm bounciness on 1.78

### ISSUE THREAD

**Issue by jonpas** [Theseus-Aegis/Mods#325]
> Tweaked: The 20mm and 40mm grenades use the 'shotShell' simulation again (muzzleImpulseFactor used to limit recoil)

**Comment by alganthe** [comment]
Not fixed, it's actually worse, some references images below:
![example 1](https://i.imgur.com/daI3fss.png)
![example 2](https://i.imgur.com/L9hMsWQ.png)
