### ISSUE TITLE
Armory - Export `getUnitLoadout`

### ISSUE THREAD

**Issue by synixebrett** [Theseus-Aegis/Mods#413]
It'd be nice to be able to export your current loadout to the clipboard, could just make a call to the ace extension that already does this. This way one could open up the arsenal from the main menu and import their loadout if one wanted to preview style changes.

**Comment by jonpas** [comment]
Nice, good idea!

I think we should add a button somewhere on bottom or top, edge of the tablet. That way it's inconspicuous and doesn't impact immersion in any way as it would have no text (just "copy" icon).

There is a background PAA in the `UI` directory, could just add to that. Or even better, make a separate PAA we can put on top. Implementation wise it's very simple anyways.
