### ISSUE TITLE
Add Stopped event for Shooting range

### ISSUE THREAD

**Issue by TyroneMF** [Theseus-Aegis/Mods#421]
Shooting range currently has [started](https://github.com/Theseus-Aegis/Mods/blob/9d297194ba6d3b835f8ec93218c5fe2d42a36eee/addons/shootingrange/functions/fnc_start.sqf#L114)

But no stopped event.

**Comment by jonpas** [comment]
Should fire always, even when cancelled.

Arguments:
- Player (runner)
- Successfully completed
- Score data (array, empty if cancelled)
