### ISSUE TITLE
TAC Mission Type executing on every mission.

### ISSUE THREAD

**Issue by Mike-MF** [Theseus-Aegis/Mods#546]
**TAC Mods Version:** 1.35.0

**Mods:**
```
- Core Pack
```

**Description:**
- Every mission with the `Mission` component loaded now throws an error because of missing `tac_type`

**Comment by jonpas** [comment]
Probably best to move that code back to template's `admin/init.sqf`. Don't see a particular use for it being here specifically.

https://github.com/Theseus-Aegis/Mods/blob/6ed80f04c7e08252960b2dd97daadb2c468d51c5/addons/mission/XEH_postInit.sqf#L3-L7
