### ISSUE TITLE
Automatic NVG equipping based on `dayTime`

### ISSUE THREAD

**Issue by Mike-MF** [Theseus-Aegis/Mods#602]
- JJ: "Make me an issue with all that info."

- Idea is to add an init EH to units so if they have NVGs in their inventory, they will automatically equip it if time is between 17:00-05:00
- Check HMD slot for vanilla units and exit if it's occupied.
- TAC Units v2.0.0 will have all factional units with NVGs inside inventory instead of immediately equipped.
- NVG baseclass: `NVGoggles`
- `sunOrMoon` & `moonIntensity` do work.
- Preferably have this available inside TACU.

**Comment by jonpas** [comment]
https://github.com/acemod/ACE3/pull/9313

**Comment by jonpas** [comment]
Temporarily put into Mods https://github.com/Theseus-Aegis/Mods/pull/615 until ACE3 version is merged and released.
